# Lint workflow - DISABLED until linter errors are fixed
# See issue: https://github.com/kwila-cloud/bintraq/issues/70

# name: Lint

# on:
#   pull_request:
#     types: [opened, reopened, synchronize]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
        
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#           cache: 'npm'
#           cache-dependency-path: app/package-lock.json
          
#       - name: Install dependencies
#         run: |
#           cd app
#           npm ci
          
#       - name: Run ESLint
#         run: |
#           cd app
#           npm run lint
          
#       - name: Run type check
#         run: |
#           cd app
#           npm run type-check
